### ISSUE TITLE
Error when loading data using python 3

### ISSUE THREAD

**Issue by prabushitha** [adithyaselv/face-expression-detect#2]
Initializing Dlib face Detector..
Loading landmark identification data...
Loading trained data.....
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle_compat.py", line 226, in load_compatibility
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.6/pickle.py", line 1226, in load_short_binstring
    self.append(self._decode_string(data))
  File "/usr/lib/python3.6/pickle.py", line 1166, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 6: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "EmoDetect.py", line 113, in <module>
    classify=joblib.load("traindata.pkl")
  File "/usr/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 573, in load
    return load_compatibility(fobj)
  File "/usr/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle_compat.py", line 235, in load_compatibility
    raise new_exc
**ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.**

**Comment by adithyaselv** [comment]
I am guessing you are running the code with python3 ! and hence the problem. Try to run using python 2 and report back

**Comment by sprtkd** [comment]
Can you please provide the code for python 3?

**Comment by adithyaselv** [comment]
Sorry ! I am not working this currently ! PRs will be accepted .
